arch: x86_64
repos:
  - core
  - extra
  - community

svn2git:
  upstream-core-extra: "https://github.com/archlinux/svntogit-packages.git"
  upstream-community: "https://github.com/archlinux/svntogit-community.git"

db:
  driver: pgx
  connect_to: "postgres://username:password@localhost:5432/database_name"

basedir:
  repo: /var/lib/alhp/repo/
  work: /var/lib/alhp/workspace/
  debug: /var/lib/alhp/debug/

march:
  - x86-64-v3

blacklist:
  packages:
    - tensorflow
    - tensorflow-cuda
    - gcc
  repo:
    - testing
    - i686
    - staging
    - unstable
  lto:
    - llvm
    - rust

status:
  class:
    skipped: "secondary"
    queued: "warning"
    latest: "primary"
    failed: "danger"
    signing: "success"
    building: "info"
    unknown: "dark"

build:
  # number of workers total
  worker: 4
  makej: 8
  checks: true
  # how much memory ALHP should use
  # this will also decide how many builds will run concurrently,
  # since ALHP will try to optimise the queue for speed while not going over this limit
  memory_limit: "16gb"

logging:
  level: INFO