// Code generated by ent, DO NOT EDIT.

package dbpackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"somegit.dev/ALHP/ALHP.GO/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldID, id))
}

// Pkgbase applies equality check predicate on the "pkgbase" field. It's identical to PkgbaseEQ.
func Pkgbase(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldPkgbase, v))
}

// SkipReason applies equality check predicate on the "skip_reason" field. It's identical to SkipReasonEQ.
func SkipReason(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldSkipReason, v))
}

// March applies equality check predicate on the "march" field. It's identical to MarchEQ.
func March(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldMarch, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldVersion, v))
}

// RepoVersion applies equality check predicate on the "repo_version" field. It's identical to RepoVersionEQ.
func RepoVersion(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldRepoVersion, v))
}

// BuildTimeStart applies equality check predicate on the "build_time_start" field. It's identical to BuildTimeStartEQ.
func BuildTimeStart(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldBuildTimeStart, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldUpdated, v))
}

// LastVersionBuild applies equality check predicate on the "last_version_build" field. It's identical to LastVersionBuildEQ.
func LastVersionBuild(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldLastVersionBuild, v))
}

// LastVerified applies equality check predicate on the "last_verified" field. It's identical to LastVerifiedEQ.
func LastVerified(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldLastVerified, v))
}

// MaxRss applies equality check predicate on the "max_rss" field. It's identical to MaxRssEQ.
func MaxRss(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldMaxRss, v))
}

// UTime applies equality check predicate on the "u_time" field. It's identical to UTimeEQ.
func UTime(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldUTime, v))
}

// STime applies equality check predicate on the "s_time" field. It's identical to STimeEQ.
func STime(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldSTime, v))
}

// IoIn applies equality check predicate on the "io_in" field. It's identical to IoInEQ.
func IoIn(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldIoIn, v))
}

// IoOut applies equality check predicate on the "io_out" field. It's identical to IoOutEQ.
func IoOut(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldIoOut, v))
}

// TagRev applies equality check predicate on the "tag_rev" field. It's identical to TagRevEQ.
func TagRev(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldTagRev, v))
}

// PkgbaseEQ applies the EQ predicate on the "pkgbase" field.
func PkgbaseEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldPkgbase, v))
}

// PkgbaseNEQ applies the NEQ predicate on the "pkgbase" field.
func PkgbaseNEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldPkgbase, v))
}

// PkgbaseIn applies the In predicate on the "pkgbase" field.
func PkgbaseIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldPkgbase, vs...))
}

// PkgbaseNotIn applies the NotIn predicate on the "pkgbase" field.
func PkgbaseNotIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldPkgbase, vs...))
}

// PkgbaseGT applies the GT predicate on the "pkgbase" field.
func PkgbaseGT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldPkgbase, v))
}

// PkgbaseGTE applies the GTE predicate on the "pkgbase" field.
func PkgbaseGTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldPkgbase, v))
}

// PkgbaseLT applies the LT predicate on the "pkgbase" field.
func PkgbaseLT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldPkgbase, v))
}

// PkgbaseLTE applies the LTE predicate on the "pkgbase" field.
func PkgbaseLTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldPkgbase, v))
}

// PkgbaseContains applies the Contains predicate on the "pkgbase" field.
func PkgbaseContains(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContains(FieldPkgbase, v))
}

// PkgbaseHasPrefix applies the HasPrefix predicate on the "pkgbase" field.
func PkgbaseHasPrefix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasPrefix(FieldPkgbase, v))
}

// PkgbaseHasSuffix applies the HasSuffix predicate on the "pkgbase" field.
func PkgbaseHasSuffix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasSuffix(FieldPkgbase, v))
}

// PkgbaseEqualFold applies the EqualFold predicate on the "pkgbase" field.
func PkgbaseEqualFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEqualFold(FieldPkgbase, v))
}

// PkgbaseContainsFold applies the ContainsFold predicate on the "pkgbase" field.
func PkgbaseContainsFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContainsFold(FieldPkgbase, v))
}

// PackagesIsNil applies the IsNil predicate on the "packages" field.
func PackagesIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldPackages))
}

// PackagesNotNil applies the NotNil predicate on the "packages" field.
func PackagesNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldPackages))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldStatus))
}

// SkipReasonEQ applies the EQ predicate on the "skip_reason" field.
func SkipReasonEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldSkipReason, v))
}

// SkipReasonNEQ applies the NEQ predicate on the "skip_reason" field.
func SkipReasonNEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldSkipReason, v))
}

// SkipReasonIn applies the In predicate on the "skip_reason" field.
func SkipReasonIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldSkipReason, vs...))
}

// SkipReasonNotIn applies the NotIn predicate on the "skip_reason" field.
func SkipReasonNotIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldSkipReason, vs...))
}

// SkipReasonGT applies the GT predicate on the "skip_reason" field.
func SkipReasonGT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldSkipReason, v))
}

// SkipReasonGTE applies the GTE predicate on the "skip_reason" field.
func SkipReasonGTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldSkipReason, v))
}

// SkipReasonLT applies the LT predicate on the "skip_reason" field.
func SkipReasonLT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldSkipReason, v))
}

// SkipReasonLTE applies the LTE predicate on the "skip_reason" field.
func SkipReasonLTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldSkipReason, v))
}

// SkipReasonContains applies the Contains predicate on the "skip_reason" field.
func SkipReasonContains(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContains(FieldSkipReason, v))
}

// SkipReasonHasPrefix applies the HasPrefix predicate on the "skip_reason" field.
func SkipReasonHasPrefix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasPrefix(FieldSkipReason, v))
}

// SkipReasonHasSuffix applies the HasSuffix predicate on the "skip_reason" field.
func SkipReasonHasSuffix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasSuffix(FieldSkipReason, v))
}

// SkipReasonIsNil applies the IsNil predicate on the "skip_reason" field.
func SkipReasonIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldSkipReason))
}

// SkipReasonNotNil applies the NotNil predicate on the "skip_reason" field.
func SkipReasonNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldSkipReason))
}

// SkipReasonEqualFold applies the EqualFold predicate on the "skip_reason" field.
func SkipReasonEqualFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEqualFold(FieldSkipReason, v))
}

// SkipReasonContainsFold applies the ContainsFold predicate on the "skip_reason" field.
func SkipReasonContainsFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContainsFold(FieldSkipReason, v))
}

// RepositoryEQ applies the EQ predicate on the "repository" field.
func RepositoryEQ(v Repository) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldRepository, v))
}

// RepositoryNEQ applies the NEQ predicate on the "repository" field.
func RepositoryNEQ(v Repository) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldRepository, v))
}

// RepositoryIn applies the In predicate on the "repository" field.
func RepositoryIn(vs ...Repository) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldRepository, vs...))
}

// RepositoryNotIn applies the NotIn predicate on the "repository" field.
func RepositoryNotIn(vs ...Repository) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldRepository, vs...))
}

// MarchEQ applies the EQ predicate on the "march" field.
func MarchEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldMarch, v))
}

// MarchNEQ applies the NEQ predicate on the "march" field.
func MarchNEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldMarch, v))
}

// MarchIn applies the In predicate on the "march" field.
func MarchIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldMarch, vs...))
}

// MarchNotIn applies the NotIn predicate on the "march" field.
func MarchNotIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldMarch, vs...))
}

// MarchGT applies the GT predicate on the "march" field.
func MarchGT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldMarch, v))
}

// MarchGTE applies the GTE predicate on the "march" field.
func MarchGTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldMarch, v))
}

// MarchLT applies the LT predicate on the "march" field.
func MarchLT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldMarch, v))
}

// MarchLTE applies the LTE predicate on the "march" field.
func MarchLTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldMarch, v))
}

// MarchContains applies the Contains predicate on the "march" field.
func MarchContains(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContains(FieldMarch, v))
}

// MarchHasPrefix applies the HasPrefix predicate on the "march" field.
func MarchHasPrefix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasPrefix(FieldMarch, v))
}

// MarchHasSuffix applies the HasSuffix predicate on the "march" field.
func MarchHasSuffix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasSuffix(FieldMarch, v))
}

// MarchEqualFold applies the EqualFold predicate on the "march" field.
func MarchEqualFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEqualFold(FieldMarch, v))
}

// MarchContainsFold applies the ContainsFold predicate on the "march" field.
func MarchContainsFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContainsFold(FieldMarch, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionIsNil applies the IsNil predicate on the "version" field.
func VersionIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldVersion))
}

// VersionNotNil applies the NotNil predicate on the "version" field.
func VersionNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldVersion))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContainsFold(FieldVersion, v))
}

// RepoVersionEQ applies the EQ predicate on the "repo_version" field.
func RepoVersionEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldRepoVersion, v))
}

// RepoVersionNEQ applies the NEQ predicate on the "repo_version" field.
func RepoVersionNEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldRepoVersion, v))
}

// RepoVersionIn applies the In predicate on the "repo_version" field.
func RepoVersionIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldRepoVersion, vs...))
}

// RepoVersionNotIn applies the NotIn predicate on the "repo_version" field.
func RepoVersionNotIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldRepoVersion, vs...))
}

// RepoVersionGT applies the GT predicate on the "repo_version" field.
func RepoVersionGT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldRepoVersion, v))
}

// RepoVersionGTE applies the GTE predicate on the "repo_version" field.
func RepoVersionGTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldRepoVersion, v))
}

// RepoVersionLT applies the LT predicate on the "repo_version" field.
func RepoVersionLT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldRepoVersion, v))
}

// RepoVersionLTE applies the LTE predicate on the "repo_version" field.
func RepoVersionLTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldRepoVersion, v))
}

// RepoVersionContains applies the Contains predicate on the "repo_version" field.
func RepoVersionContains(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContains(FieldRepoVersion, v))
}

// RepoVersionHasPrefix applies the HasPrefix predicate on the "repo_version" field.
func RepoVersionHasPrefix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasPrefix(FieldRepoVersion, v))
}

// RepoVersionHasSuffix applies the HasSuffix predicate on the "repo_version" field.
func RepoVersionHasSuffix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasSuffix(FieldRepoVersion, v))
}

// RepoVersionIsNil applies the IsNil predicate on the "repo_version" field.
func RepoVersionIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldRepoVersion))
}

// RepoVersionNotNil applies the NotNil predicate on the "repo_version" field.
func RepoVersionNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldRepoVersion))
}

// RepoVersionEqualFold applies the EqualFold predicate on the "repo_version" field.
func RepoVersionEqualFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEqualFold(FieldRepoVersion, v))
}

// RepoVersionContainsFold applies the ContainsFold predicate on the "repo_version" field.
func RepoVersionContainsFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContainsFold(FieldRepoVersion, v))
}

// BuildTimeStartEQ applies the EQ predicate on the "build_time_start" field.
func BuildTimeStartEQ(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldBuildTimeStart, v))
}

// BuildTimeStartNEQ applies the NEQ predicate on the "build_time_start" field.
func BuildTimeStartNEQ(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldBuildTimeStart, v))
}

// BuildTimeStartIn applies the In predicate on the "build_time_start" field.
func BuildTimeStartIn(vs ...time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldBuildTimeStart, vs...))
}

// BuildTimeStartNotIn applies the NotIn predicate on the "build_time_start" field.
func BuildTimeStartNotIn(vs ...time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldBuildTimeStart, vs...))
}

// BuildTimeStartGT applies the GT predicate on the "build_time_start" field.
func BuildTimeStartGT(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldBuildTimeStart, v))
}

// BuildTimeStartGTE applies the GTE predicate on the "build_time_start" field.
func BuildTimeStartGTE(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldBuildTimeStart, v))
}

// BuildTimeStartLT applies the LT predicate on the "build_time_start" field.
func BuildTimeStartLT(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldBuildTimeStart, v))
}

// BuildTimeStartLTE applies the LTE predicate on the "build_time_start" field.
func BuildTimeStartLTE(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldBuildTimeStart, v))
}

// BuildTimeStartIsNil applies the IsNil predicate on the "build_time_start" field.
func BuildTimeStartIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldBuildTimeStart))
}

// BuildTimeStartNotNil applies the NotNil predicate on the "build_time_start" field.
func BuildTimeStartNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldBuildTimeStart))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldUpdated, v))
}

// UpdatedIsNil applies the IsNil predicate on the "updated" field.
func UpdatedIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldUpdated))
}

// UpdatedNotNil applies the NotNil predicate on the "updated" field.
func UpdatedNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldUpdated))
}

// LtoEQ applies the EQ predicate on the "lto" field.
func LtoEQ(v Lto) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldLto, v))
}

// LtoNEQ applies the NEQ predicate on the "lto" field.
func LtoNEQ(v Lto) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldLto, v))
}

// LtoIn applies the In predicate on the "lto" field.
func LtoIn(vs ...Lto) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldLto, vs...))
}

// LtoNotIn applies the NotIn predicate on the "lto" field.
func LtoNotIn(vs ...Lto) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldLto, vs...))
}

// LtoIsNil applies the IsNil predicate on the "lto" field.
func LtoIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldLto))
}

// LtoNotNil applies the NotNil predicate on the "lto" field.
func LtoNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldLto))
}

// LastVersionBuildEQ applies the EQ predicate on the "last_version_build" field.
func LastVersionBuildEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldLastVersionBuild, v))
}

// LastVersionBuildNEQ applies the NEQ predicate on the "last_version_build" field.
func LastVersionBuildNEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldLastVersionBuild, v))
}

// LastVersionBuildIn applies the In predicate on the "last_version_build" field.
func LastVersionBuildIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldLastVersionBuild, vs...))
}

// LastVersionBuildNotIn applies the NotIn predicate on the "last_version_build" field.
func LastVersionBuildNotIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldLastVersionBuild, vs...))
}

// LastVersionBuildGT applies the GT predicate on the "last_version_build" field.
func LastVersionBuildGT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldLastVersionBuild, v))
}

// LastVersionBuildGTE applies the GTE predicate on the "last_version_build" field.
func LastVersionBuildGTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldLastVersionBuild, v))
}

// LastVersionBuildLT applies the LT predicate on the "last_version_build" field.
func LastVersionBuildLT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldLastVersionBuild, v))
}

// LastVersionBuildLTE applies the LTE predicate on the "last_version_build" field.
func LastVersionBuildLTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldLastVersionBuild, v))
}

// LastVersionBuildContains applies the Contains predicate on the "last_version_build" field.
func LastVersionBuildContains(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContains(FieldLastVersionBuild, v))
}

// LastVersionBuildHasPrefix applies the HasPrefix predicate on the "last_version_build" field.
func LastVersionBuildHasPrefix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasPrefix(FieldLastVersionBuild, v))
}

// LastVersionBuildHasSuffix applies the HasSuffix predicate on the "last_version_build" field.
func LastVersionBuildHasSuffix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasSuffix(FieldLastVersionBuild, v))
}

// LastVersionBuildIsNil applies the IsNil predicate on the "last_version_build" field.
func LastVersionBuildIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldLastVersionBuild))
}

// LastVersionBuildNotNil applies the NotNil predicate on the "last_version_build" field.
func LastVersionBuildNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldLastVersionBuild))
}

// LastVersionBuildEqualFold applies the EqualFold predicate on the "last_version_build" field.
func LastVersionBuildEqualFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEqualFold(FieldLastVersionBuild, v))
}

// LastVersionBuildContainsFold applies the ContainsFold predicate on the "last_version_build" field.
func LastVersionBuildContainsFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContainsFold(FieldLastVersionBuild, v))
}

// LastVerifiedEQ applies the EQ predicate on the "last_verified" field.
func LastVerifiedEQ(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldLastVerified, v))
}

// LastVerifiedNEQ applies the NEQ predicate on the "last_verified" field.
func LastVerifiedNEQ(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldLastVerified, v))
}

// LastVerifiedIn applies the In predicate on the "last_verified" field.
func LastVerifiedIn(vs ...time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldLastVerified, vs...))
}

// LastVerifiedNotIn applies the NotIn predicate on the "last_verified" field.
func LastVerifiedNotIn(vs ...time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldLastVerified, vs...))
}

// LastVerifiedGT applies the GT predicate on the "last_verified" field.
func LastVerifiedGT(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldLastVerified, v))
}

// LastVerifiedGTE applies the GTE predicate on the "last_verified" field.
func LastVerifiedGTE(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldLastVerified, v))
}

// LastVerifiedLT applies the LT predicate on the "last_verified" field.
func LastVerifiedLT(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldLastVerified, v))
}

// LastVerifiedLTE applies the LTE predicate on the "last_verified" field.
func LastVerifiedLTE(v time.Time) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldLastVerified, v))
}

// LastVerifiedIsNil applies the IsNil predicate on the "last_verified" field.
func LastVerifiedIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldLastVerified))
}

// LastVerifiedNotNil applies the NotNil predicate on the "last_verified" field.
func LastVerifiedNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldLastVerified))
}

// DebugSymbolsEQ applies the EQ predicate on the "debug_symbols" field.
func DebugSymbolsEQ(v DebugSymbols) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldDebugSymbols, v))
}

// DebugSymbolsNEQ applies the NEQ predicate on the "debug_symbols" field.
func DebugSymbolsNEQ(v DebugSymbols) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldDebugSymbols, v))
}

// DebugSymbolsIn applies the In predicate on the "debug_symbols" field.
func DebugSymbolsIn(vs ...DebugSymbols) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldDebugSymbols, vs...))
}

// DebugSymbolsNotIn applies the NotIn predicate on the "debug_symbols" field.
func DebugSymbolsNotIn(vs ...DebugSymbols) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldDebugSymbols, vs...))
}

// DebugSymbolsIsNil applies the IsNil predicate on the "debug_symbols" field.
func DebugSymbolsIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldDebugSymbols))
}

// DebugSymbolsNotNil applies the NotNil predicate on the "debug_symbols" field.
func DebugSymbolsNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldDebugSymbols))
}

// MaxRssEQ applies the EQ predicate on the "max_rss" field.
func MaxRssEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldMaxRss, v))
}

// MaxRssNEQ applies the NEQ predicate on the "max_rss" field.
func MaxRssNEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldMaxRss, v))
}

// MaxRssIn applies the In predicate on the "max_rss" field.
func MaxRssIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldMaxRss, vs...))
}

// MaxRssNotIn applies the NotIn predicate on the "max_rss" field.
func MaxRssNotIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldMaxRss, vs...))
}

// MaxRssGT applies the GT predicate on the "max_rss" field.
func MaxRssGT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldMaxRss, v))
}

// MaxRssGTE applies the GTE predicate on the "max_rss" field.
func MaxRssGTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldMaxRss, v))
}

// MaxRssLT applies the LT predicate on the "max_rss" field.
func MaxRssLT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldMaxRss, v))
}

// MaxRssLTE applies the LTE predicate on the "max_rss" field.
func MaxRssLTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldMaxRss, v))
}

// MaxRssIsNil applies the IsNil predicate on the "max_rss" field.
func MaxRssIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldMaxRss))
}

// MaxRssNotNil applies the NotNil predicate on the "max_rss" field.
func MaxRssNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldMaxRss))
}

// UTimeEQ applies the EQ predicate on the "u_time" field.
func UTimeEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldUTime, v))
}

// UTimeNEQ applies the NEQ predicate on the "u_time" field.
func UTimeNEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldUTime, v))
}

// UTimeIn applies the In predicate on the "u_time" field.
func UTimeIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldUTime, vs...))
}

// UTimeNotIn applies the NotIn predicate on the "u_time" field.
func UTimeNotIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldUTime, vs...))
}

// UTimeGT applies the GT predicate on the "u_time" field.
func UTimeGT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldUTime, v))
}

// UTimeGTE applies the GTE predicate on the "u_time" field.
func UTimeGTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldUTime, v))
}

// UTimeLT applies the LT predicate on the "u_time" field.
func UTimeLT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldUTime, v))
}

// UTimeLTE applies the LTE predicate on the "u_time" field.
func UTimeLTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldUTime, v))
}

// UTimeIsNil applies the IsNil predicate on the "u_time" field.
func UTimeIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldUTime))
}

// UTimeNotNil applies the NotNil predicate on the "u_time" field.
func UTimeNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldUTime))
}

// STimeEQ applies the EQ predicate on the "s_time" field.
func STimeEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldSTime, v))
}

// STimeNEQ applies the NEQ predicate on the "s_time" field.
func STimeNEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldSTime, v))
}

// STimeIn applies the In predicate on the "s_time" field.
func STimeIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldSTime, vs...))
}

// STimeNotIn applies the NotIn predicate on the "s_time" field.
func STimeNotIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldSTime, vs...))
}

// STimeGT applies the GT predicate on the "s_time" field.
func STimeGT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldSTime, v))
}

// STimeGTE applies the GTE predicate on the "s_time" field.
func STimeGTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldSTime, v))
}

// STimeLT applies the LT predicate on the "s_time" field.
func STimeLT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldSTime, v))
}

// STimeLTE applies the LTE predicate on the "s_time" field.
func STimeLTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldSTime, v))
}

// STimeIsNil applies the IsNil predicate on the "s_time" field.
func STimeIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldSTime))
}

// STimeNotNil applies the NotNil predicate on the "s_time" field.
func STimeNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldSTime))
}

// IoInEQ applies the EQ predicate on the "io_in" field.
func IoInEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldIoIn, v))
}

// IoInNEQ applies the NEQ predicate on the "io_in" field.
func IoInNEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldIoIn, v))
}

// IoInIn applies the In predicate on the "io_in" field.
func IoInIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldIoIn, vs...))
}

// IoInNotIn applies the NotIn predicate on the "io_in" field.
func IoInNotIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldIoIn, vs...))
}

// IoInGT applies the GT predicate on the "io_in" field.
func IoInGT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldIoIn, v))
}

// IoInGTE applies the GTE predicate on the "io_in" field.
func IoInGTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldIoIn, v))
}

// IoInLT applies the LT predicate on the "io_in" field.
func IoInLT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldIoIn, v))
}

// IoInLTE applies the LTE predicate on the "io_in" field.
func IoInLTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldIoIn, v))
}

// IoInIsNil applies the IsNil predicate on the "io_in" field.
func IoInIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldIoIn))
}

// IoInNotNil applies the NotNil predicate on the "io_in" field.
func IoInNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldIoIn))
}

// IoOutEQ applies the EQ predicate on the "io_out" field.
func IoOutEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldIoOut, v))
}

// IoOutNEQ applies the NEQ predicate on the "io_out" field.
func IoOutNEQ(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldIoOut, v))
}

// IoOutIn applies the In predicate on the "io_out" field.
func IoOutIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldIoOut, vs...))
}

// IoOutNotIn applies the NotIn predicate on the "io_out" field.
func IoOutNotIn(vs ...int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldIoOut, vs...))
}

// IoOutGT applies the GT predicate on the "io_out" field.
func IoOutGT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldIoOut, v))
}

// IoOutGTE applies the GTE predicate on the "io_out" field.
func IoOutGTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldIoOut, v))
}

// IoOutLT applies the LT predicate on the "io_out" field.
func IoOutLT(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldIoOut, v))
}

// IoOutLTE applies the LTE predicate on the "io_out" field.
func IoOutLTE(v int64) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldIoOut, v))
}

// IoOutIsNil applies the IsNil predicate on the "io_out" field.
func IoOutIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldIoOut))
}

// IoOutNotNil applies the NotNil predicate on the "io_out" field.
func IoOutNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldIoOut))
}

// TagRevEQ applies the EQ predicate on the "tag_rev" field.
func TagRevEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEQ(FieldTagRev, v))
}

// TagRevNEQ applies the NEQ predicate on the "tag_rev" field.
func TagRevNEQ(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNEQ(FieldTagRev, v))
}

// TagRevIn applies the In predicate on the "tag_rev" field.
func TagRevIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIn(FieldTagRev, vs...))
}

// TagRevNotIn applies the NotIn predicate on the "tag_rev" field.
func TagRevNotIn(vs ...string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotIn(FieldTagRev, vs...))
}

// TagRevGT applies the GT predicate on the "tag_rev" field.
func TagRevGT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGT(FieldTagRev, v))
}

// TagRevGTE applies the GTE predicate on the "tag_rev" field.
func TagRevGTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldGTE(FieldTagRev, v))
}

// TagRevLT applies the LT predicate on the "tag_rev" field.
func TagRevLT(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLT(FieldTagRev, v))
}

// TagRevLTE applies the LTE predicate on the "tag_rev" field.
func TagRevLTE(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldLTE(FieldTagRev, v))
}

// TagRevContains applies the Contains predicate on the "tag_rev" field.
func TagRevContains(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContains(FieldTagRev, v))
}

// TagRevHasPrefix applies the HasPrefix predicate on the "tag_rev" field.
func TagRevHasPrefix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasPrefix(FieldTagRev, v))
}

// TagRevHasSuffix applies the HasSuffix predicate on the "tag_rev" field.
func TagRevHasSuffix(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldHasSuffix(FieldTagRev, v))
}

// TagRevIsNil applies the IsNil predicate on the "tag_rev" field.
func TagRevIsNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldIsNull(FieldTagRev))
}

// TagRevNotNil applies the NotNil predicate on the "tag_rev" field.
func TagRevNotNil() predicate.DBPackage {
	return predicate.DBPackage(sql.FieldNotNull(FieldTagRev))
}

// TagRevEqualFold applies the EqualFold predicate on the "tag_rev" field.
func TagRevEqualFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldEqualFold(FieldTagRev, v))
}

// TagRevContainsFold applies the ContainsFold predicate on the "tag_rev" field.
func TagRevContainsFold(v string) predicate.DBPackage {
	return predicate.DBPackage(sql.FieldContainsFold(FieldTagRev, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DBPackage) predicate.DBPackage {
	return predicate.DBPackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DBPackage) predicate.DBPackage {
	return predicate.DBPackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DBPackage) predicate.DBPackage {
	return predicate.DBPackage(sql.NotPredicates(p))
}
