// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"somegit.dev/ALHP/ALHP.GO/ent/dbpackage"
	"somegit.dev/ALHP/ALHP.GO/ent/predicate"
)

// DBPackageUpdate is the builder for updating DBPackage entities.
type DBPackageUpdate struct {
	config
	hooks     []Hook
	mutation  *DBPackageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DBPackageUpdate builder.
func (_u *DBPackageUpdate) Where(ps ...predicate.DBPackage) *DBPackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackages sets the "packages" field.
func (_u *DBPackageUpdate) SetPackages(v []string) *DBPackageUpdate {
	_u.mutation.SetPackages(v)
	return _u
}

// AppendPackages appends value to the "packages" field.
func (_u *DBPackageUpdate) AppendPackages(v []string) *DBPackageUpdate {
	_u.mutation.AppendPackages(v)
	return _u
}

// ClearPackages clears the value of the "packages" field.
func (_u *DBPackageUpdate) ClearPackages() *DBPackageUpdate {
	_u.mutation.ClearPackages()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DBPackageUpdate) SetStatus(v dbpackage.Status) *DBPackageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableStatus(v *dbpackage.Status) *DBPackageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *DBPackageUpdate) ClearStatus() *DBPackageUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetSkipReason sets the "skip_reason" field.
func (_u *DBPackageUpdate) SetSkipReason(v string) *DBPackageUpdate {
	_u.mutation.SetSkipReason(v)
	return _u
}

// SetNillableSkipReason sets the "skip_reason" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableSkipReason(v *string) *DBPackageUpdate {
	if v != nil {
		_u.SetSkipReason(*v)
	}
	return _u
}

// ClearSkipReason clears the value of the "skip_reason" field.
func (_u *DBPackageUpdate) ClearSkipReason() *DBPackageUpdate {
	_u.mutation.ClearSkipReason()
	return _u
}

// SetRepository sets the "repository" field.
func (_u *DBPackageUpdate) SetRepository(v dbpackage.Repository) *DBPackageUpdate {
	_u.mutation.SetRepository(v)
	return _u
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableRepository(v *dbpackage.Repository) *DBPackageUpdate {
	if v != nil {
		_u.SetRepository(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *DBPackageUpdate) SetVersion(v string) *DBPackageUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableVersion(v *string) *DBPackageUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *DBPackageUpdate) ClearVersion() *DBPackageUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetRepoVersion sets the "repo_version" field.
func (_u *DBPackageUpdate) SetRepoVersion(v string) *DBPackageUpdate {
	_u.mutation.SetRepoVersion(v)
	return _u
}

// SetNillableRepoVersion sets the "repo_version" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableRepoVersion(v *string) *DBPackageUpdate {
	if v != nil {
		_u.SetRepoVersion(*v)
	}
	return _u
}

// ClearRepoVersion clears the value of the "repo_version" field.
func (_u *DBPackageUpdate) ClearRepoVersion() *DBPackageUpdate {
	_u.mutation.ClearRepoVersion()
	return _u
}

// SetBuildTimeStart sets the "build_time_start" field.
func (_u *DBPackageUpdate) SetBuildTimeStart(v time.Time) *DBPackageUpdate {
	_u.mutation.SetBuildTimeStart(v)
	return _u
}

// SetNillableBuildTimeStart sets the "build_time_start" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableBuildTimeStart(v *time.Time) *DBPackageUpdate {
	if v != nil {
		_u.SetBuildTimeStart(*v)
	}
	return _u
}

// ClearBuildTimeStart clears the value of the "build_time_start" field.
func (_u *DBPackageUpdate) ClearBuildTimeStart() *DBPackageUpdate {
	_u.mutation.ClearBuildTimeStart()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *DBPackageUpdate) SetUpdated(v time.Time) *DBPackageUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableUpdated(v *time.Time) *DBPackageUpdate {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// ClearUpdated clears the value of the "updated" field.
func (_u *DBPackageUpdate) ClearUpdated() *DBPackageUpdate {
	_u.mutation.ClearUpdated()
	return _u
}

// SetLto sets the "lto" field.
func (_u *DBPackageUpdate) SetLto(v dbpackage.Lto) *DBPackageUpdate {
	_u.mutation.SetLto(v)
	return _u
}

// SetNillableLto sets the "lto" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableLto(v *dbpackage.Lto) *DBPackageUpdate {
	if v != nil {
		_u.SetLto(*v)
	}
	return _u
}

// ClearLto clears the value of the "lto" field.
func (_u *DBPackageUpdate) ClearLto() *DBPackageUpdate {
	_u.mutation.ClearLto()
	return _u
}

// SetLastVersionBuild sets the "last_version_build" field.
func (_u *DBPackageUpdate) SetLastVersionBuild(v string) *DBPackageUpdate {
	_u.mutation.SetLastVersionBuild(v)
	return _u
}

// SetNillableLastVersionBuild sets the "last_version_build" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableLastVersionBuild(v *string) *DBPackageUpdate {
	if v != nil {
		_u.SetLastVersionBuild(*v)
	}
	return _u
}

// ClearLastVersionBuild clears the value of the "last_version_build" field.
func (_u *DBPackageUpdate) ClearLastVersionBuild() *DBPackageUpdate {
	_u.mutation.ClearLastVersionBuild()
	return _u
}

// SetLastVerified sets the "last_verified" field.
func (_u *DBPackageUpdate) SetLastVerified(v time.Time) *DBPackageUpdate {
	_u.mutation.SetLastVerified(v)
	return _u
}

// SetNillableLastVerified sets the "last_verified" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableLastVerified(v *time.Time) *DBPackageUpdate {
	if v != nil {
		_u.SetLastVerified(*v)
	}
	return _u
}

// ClearLastVerified clears the value of the "last_verified" field.
func (_u *DBPackageUpdate) ClearLastVerified() *DBPackageUpdate {
	_u.mutation.ClearLastVerified()
	return _u
}

// SetDebugSymbols sets the "debug_symbols" field.
func (_u *DBPackageUpdate) SetDebugSymbols(v dbpackage.DebugSymbols) *DBPackageUpdate {
	_u.mutation.SetDebugSymbols(v)
	return _u
}

// SetNillableDebugSymbols sets the "debug_symbols" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableDebugSymbols(v *dbpackage.DebugSymbols) *DBPackageUpdate {
	if v != nil {
		_u.SetDebugSymbols(*v)
	}
	return _u
}

// ClearDebugSymbols clears the value of the "debug_symbols" field.
func (_u *DBPackageUpdate) ClearDebugSymbols() *DBPackageUpdate {
	_u.mutation.ClearDebugSymbols()
	return _u
}

// SetMaxRss sets the "max_rss" field.
func (_u *DBPackageUpdate) SetMaxRss(v int64) *DBPackageUpdate {
	_u.mutation.ResetMaxRss()
	_u.mutation.SetMaxRss(v)
	return _u
}

// SetNillableMaxRss sets the "max_rss" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableMaxRss(v *int64) *DBPackageUpdate {
	if v != nil {
		_u.SetMaxRss(*v)
	}
	return _u
}

// AddMaxRss adds value to the "max_rss" field.
func (_u *DBPackageUpdate) AddMaxRss(v int64) *DBPackageUpdate {
	_u.mutation.AddMaxRss(v)
	return _u
}

// ClearMaxRss clears the value of the "max_rss" field.
func (_u *DBPackageUpdate) ClearMaxRss() *DBPackageUpdate {
	_u.mutation.ClearMaxRss()
	return _u
}

// SetUTime sets the "u_time" field.
func (_u *DBPackageUpdate) SetUTime(v int64) *DBPackageUpdate {
	_u.mutation.ResetUTime()
	_u.mutation.SetUTime(v)
	return _u
}

// SetNillableUTime sets the "u_time" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableUTime(v *int64) *DBPackageUpdate {
	if v != nil {
		_u.SetUTime(*v)
	}
	return _u
}

// AddUTime adds value to the "u_time" field.
func (_u *DBPackageUpdate) AddUTime(v int64) *DBPackageUpdate {
	_u.mutation.AddUTime(v)
	return _u
}

// ClearUTime clears the value of the "u_time" field.
func (_u *DBPackageUpdate) ClearUTime() *DBPackageUpdate {
	_u.mutation.ClearUTime()
	return _u
}

// SetSTime sets the "s_time" field.
func (_u *DBPackageUpdate) SetSTime(v int64) *DBPackageUpdate {
	_u.mutation.ResetSTime()
	_u.mutation.SetSTime(v)
	return _u
}

// SetNillableSTime sets the "s_time" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableSTime(v *int64) *DBPackageUpdate {
	if v != nil {
		_u.SetSTime(*v)
	}
	return _u
}

// AddSTime adds value to the "s_time" field.
func (_u *DBPackageUpdate) AddSTime(v int64) *DBPackageUpdate {
	_u.mutation.AddSTime(v)
	return _u
}

// ClearSTime clears the value of the "s_time" field.
func (_u *DBPackageUpdate) ClearSTime() *DBPackageUpdate {
	_u.mutation.ClearSTime()
	return _u
}

// SetIoIn sets the "io_in" field.
func (_u *DBPackageUpdate) SetIoIn(v int64) *DBPackageUpdate {
	_u.mutation.ResetIoIn()
	_u.mutation.SetIoIn(v)
	return _u
}

// SetNillableIoIn sets the "io_in" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableIoIn(v *int64) *DBPackageUpdate {
	if v != nil {
		_u.SetIoIn(*v)
	}
	return _u
}

// AddIoIn adds value to the "io_in" field.
func (_u *DBPackageUpdate) AddIoIn(v int64) *DBPackageUpdate {
	_u.mutation.AddIoIn(v)
	return _u
}

// ClearIoIn clears the value of the "io_in" field.
func (_u *DBPackageUpdate) ClearIoIn() *DBPackageUpdate {
	_u.mutation.ClearIoIn()
	return _u
}

// SetIoOut sets the "io_out" field.
func (_u *DBPackageUpdate) SetIoOut(v int64) *DBPackageUpdate {
	_u.mutation.ResetIoOut()
	_u.mutation.SetIoOut(v)
	return _u
}

// SetNillableIoOut sets the "io_out" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableIoOut(v *int64) *DBPackageUpdate {
	if v != nil {
		_u.SetIoOut(*v)
	}
	return _u
}

// AddIoOut adds value to the "io_out" field.
func (_u *DBPackageUpdate) AddIoOut(v int64) *DBPackageUpdate {
	_u.mutation.AddIoOut(v)
	return _u
}

// ClearIoOut clears the value of the "io_out" field.
func (_u *DBPackageUpdate) ClearIoOut() *DBPackageUpdate {
	_u.mutation.ClearIoOut()
	return _u
}

// SetTagRev sets the "tag_rev" field.
func (_u *DBPackageUpdate) SetTagRev(v string) *DBPackageUpdate {
	_u.mutation.SetTagRev(v)
	return _u
}

// SetNillableTagRev sets the "tag_rev" field if the given value is not nil.
func (_u *DBPackageUpdate) SetNillableTagRev(v *string) *DBPackageUpdate {
	if v != nil {
		_u.SetTagRev(*v)
	}
	return _u
}

// ClearTagRev clears the value of the "tag_rev" field.
func (_u *DBPackageUpdate) ClearTagRev() *DBPackageUpdate {
	_u.mutation.ClearTagRev()
	return _u
}

// Mutation returns the DBPackageMutation object of the builder.
func (_u *DBPackageUpdate) Mutation() *DBPackageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DBPackageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DBPackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DBPackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DBPackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DBPackageUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dbpackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DBPackage.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Repository(); ok {
		if err := dbpackage.RepositoryValidator(v); err != nil {
			return &ValidationError{Name: "repository", err: fmt.Errorf(`ent: validator failed for field "DBPackage.repository": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lto(); ok {
		if err := dbpackage.LtoValidator(v); err != nil {
			return &ValidationError{Name: "lto", err: fmt.Errorf(`ent: validator failed for field "DBPackage.lto": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DebugSymbols(); ok {
		if err := dbpackage.DebugSymbolsValidator(v); err != nil {
			return &ValidationError{Name: "debug_symbols", err: fmt.Errorf(`ent: validator failed for field "DBPackage.debug_symbols": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DBPackageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DBPackageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DBPackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dbpackage.Table, dbpackage.Columns, sqlgraph.NewFieldSpec(dbpackage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Packages(); ok {
		_spec.SetField(dbpackage.FieldPackages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPackages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dbpackage.FieldPackages, value)
		})
	}
	if _u.mutation.PackagesCleared() {
		_spec.ClearField(dbpackage.FieldPackages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dbpackage.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(dbpackage.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.SkipReason(); ok {
		_spec.SetField(dbpackage.FieldSkipReason, field.TypeString, value)
	}
	if _u.mutation.SkipReasonCleared() {
		_spec.ClearField(dbpackage.FieldSkipReason, field.TypeString)
	}
	if value, ok := _u.mutation.Repository(); ok {
		_spec.SetField(dbpackage.FieldRepository, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(dbpackage.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(dbpackage.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.RepoVersion(); ok {
		_spec.SetField(dbpackage.FieldRepoVersion, field.TypeString, value)
	}
	if _u.mutation.RepoVersionCleared() {
		_spec.ClearField(dbpackage.FieldRepoVersion, field.TypeString)
	}
	if value, ok := _u.mutation.BuildTimeStart(); ok {
		_spec.SetField(dbpackage.FieldBuildTimeStart, field.TypeTime, value)
	}
	if _u.mutation.BuildTimeStartCleared() {
		_spec.ClearField(dbpackage.FieldBuildTimeStart, field.TypeTime)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(dbpackage.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UpdatedCleared() {
		_spec.ClearField(dbpackage.FieldUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Lto(); ok {
		_spec.SetField(dbpackage.FieldLto, field.TypeEnum, value)
	}
	if _u.mutation.LtoCleared() {
		_spec.ClearField(dbpackage.FieldLto, field.TypeEnum)
	}
	if value, ok := _u.mutation.LastVersionBuild(); ok {
		_spec.SetField(dbpackage.FieldLastVersionBuild, field.TypeString, value)
	}
	if _u.mutation.LastVersionBuildCleared() {
		_spec.ClearField(dbpackage.FieldLastVersionBuild, field.TypeString)
	}
	if value, ok := _u.mutation.LastVerified(); ok {
		_spec.SetField(dbpackage.FieldLastVerified, field.TypeTime, value)
	}
	if _u.mutation.LastVerifiedCleared() {
		_spec.ClearField(dbpackage.FieldLastVerified, field.TypeTime)
	}
	if value, ok := _u.mutation.DebugSymbols(); ok {
		_spec.SetField(dbpackage.FieldDebugSymbols, field.TypeEnum, value)
	}
	if _u.mutation.DebugSymbolsCleared() {
		_spec.ClearField(dbpackage.FieldDebugSymbols, field.TypeEnum)
	}
	if value, ok := _u.mutation.MaxRss(); ok {
		_spec.SetField(dbpackage.FieldMaxRss, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxRss(); ok {
		_spec.AddField(dbpackage.FieldMaxRss, field.TypeInt64, value)
	}
	if _u.mutation.MaxRssCleared() {
		_spec.ClearField(dbpackage.FieldMaxRss, field.TypeInt64)
	}
	if value, ok := _u.mutation.UTime(); ok {
		_spec.SetField(dbpackage.FieldUTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUTime(); ok {
		_spec.AddField(dbpackage.FieldUTime, field.TypeInt64, value)
	}
	if _u.mutation.UTimeCleared() {
		_spec.ClearField(dbpackage.FieldUTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.STime(); ok {
		_spec.SetField(dbpackage.FieldSTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSTime(); ok {
		_spec.AddField(dbpackage.FieldSTime, field.TypeInt64, value)
	}
	if _u.mutation.STimeCleared() {
		_spec.ClearField(dbpackage.FieldSTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.IoIn(); ok {
		_spec.SetField(dbpackage.FieldIoIn, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIoIn(); ok {
		_spec.AddField(dbpackage.FieldIoIn, field.TypeInt64, value)
	}
	if _u.mutation.IoInCleared() {
		_spec.ClearField(dbpackage.FieldIoIn, field.TypeInt64)
	}
	if value, ok := _u.mutation.IoOut(); ok {
		_spec.SetField(dbpackage.FieldIoOut, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIoOut(); ok {
		_spec.AddField(dbpackage.FieldIoOut, field.TypeInt64, value)
	}
	if _u.mutation.IoOutCleared() {
		_spec.ClearField(dbpackage.FieldIoOut, field.TypeInt64)
	}
	if value, ok := _u.mutation.TagRev(); ok {
		_spec.SetField(dbpackage.FieldTagRev, field.TypeString, value)
	}
	if _u.mutation.TagRevCleared() {
		_spec.ClearField(dbpackage.FieldTagRev, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dbpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DBPackageUpdateOne is the builder for updating a single DBPackage entity.
type DBPackageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DBPackageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetPackages sets the "packages" field.
func (_u *DBPackageUpdateOne) SetPackages(v []string) *DBPackageUpdateOne {
	_u.mutation.SetPackages(v)
	return _u
}

// AppendPackages appends value to the "packages" field.
func (_u *DBPackageUpdateOne) AppendPackages(v []string) *DBPackageUpdateOne {
	_u.mutation.AppendPackages(v)
	return _u
}

// ClearPackages clears the value of the "packages" field.
func (_u *DBPackageUpdateOne) ClearPackages() *DBPackageUpdateOne {
	_u.mutation.ClearPackages()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DBPackageUpdateOne) SetStatus(v dbpackage.Status) *DBPackageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableStatus(v *dbpackage.Status) *DBPackageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *DBPackageUpdateOne) ClearStatus() *DBPackageUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetSkipReason sets the "skip_reason" field.
func (_u *DBPackageUpdateOne) SetSkipReason(v string) *DBPackageUpdateOne {
	_u.mutation.SetSkipReason(v)
	return _u
}

// SetNillableSkipReason sets the "skip_reason" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableSkipReason(v *string) *DBPackageUpdateOne {
	if v != nil {
		_u.SetSkipReason(*v)
	}
	return _u
}

// ClearSkipReason clears the value of the "skip_reason" field.
func (_u *DBPackageUpdateOne) ClearSkipReason() *DBPackageUpdateOne {
	_u.mutation.ClearSkipReason()
	return _u
}

// SetRepository sets the "repository" field.
func (_u *DBPackageUpdateOne) SetRepository(v dbpackage.Repository) *DBPackageUpdateOne {
	_u.mutation.SetRepository(v)
	return _u
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableRepository(v *dbpackage.Repository) *DBPackageUpdateOne {
	if v != nil {
		_u.SetRepository(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *DBPackageUpdateOne) SetVersion(v string) *DBPackageUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableVersion(v *string) *DBPackageUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *DBPackageUpdateOne) ClearVersion() *DBPackageUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetRepoVersion sets the "repo_version" field.
func (_u *DBPackageUpdateOne) SetRepoVersion(v string) *DBPackageUpdateOne {
	_u.mutation.SetRepoVersion(v)
	return _u
}

// SetNillableRepoVersion sets the "repo_version" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableRepoVersion(v *string) *DBPackageUpdateOne {
	if v != nil {
		_u.SetRepoVersion(*v)
	}
	return _u
}

// ClearRepoVersion clears the value of the "repo_version" field.
func (_u *DBPackageUpdateOne) ClearRepoVersion() *DBPackageUpdateOne {
	_u.mutation.ClearRepoVersion()
	return _u
}

// SetBuildTimeStart sets the "build_time_start" field.
func (_u *DBPackageUpdateOne) SetBuildTimeStart(v time.Time) *DBPackageUpdateOne {
	_u.mutation.SetBuildTimeStart(v)
	return _u
}

// SetNillableBuildTimeStart sets the "build_time_start" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableBuildTimeStart(v *time.Time) *DBPackageUpdateOne {
	if v != nil {
		_u.SetBuildTimeStart(*v)
	}
	return _u
}

// ClearBuildTimeStart clears the value of the "build_time_start" field.
func (_u *DBPackageUpdateOne) ClearBuildTimeStart() *DBPackageUpdateOne {
	_u.mutation.ClearBuildTimeStart()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *DBPackageUpdateOne) SetUpdated(v time.Time) *DBPackageUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableUpdated(v *time.Time) *DBPackageUpdateOne {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// ClearUpdated clears the value of the "updated" field.
func (_u *DBPackageUpdateOne) ClearUpdated() *DBPackageUpdateOne {
	_u.mutation.ClearUpdated()
	return _u
}

// SetLto sets the "lto" field.
func (_u *DBPackageUpdateOne) SetLto(v dbpackage.Lto) *DBPackageUpdateOne {
	_u.mutation.SetLto(v)
	return _u
}

// SetNillableLto sets the "lto" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableLto(v *dbpackage.Lto) *DBPackageUpdateOne {
	if v != nil {
		_u.SetLto(*v)
	}
	return _u
}

// ClearLto clears the value of the "lto" field.
func (_u *DBPackageUpdateOne) ClearLto() *DBPackageUpdateOne {
	_u.mutation.ClearLto()
	return _u
}

// SetLastVersionBuild sets the "last_version_build" field.
func (_u *DBPackageUpdateOne) SetLastVersionBuild(v string) *DBPackageUpdateOne {
	_u.mutation.SetLastVersionBuild(v)
	return _u
}

// SetNillableLastVersionBuild sets the "last_version_build" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableLastVersionBuild(v *string) *DBPackageUpdateOne {
	if v != nil {
		_u.SetLastVersionBuild(*v)
	}
	return _u
}

// ClearLastVersionBuild clears the value of the "last_version_build" field.
func (_u *DBPackageUpdateOne) ClearLastVersionBuild() *DBPackageUpdateOne {
	_u.mutation.ClearLastVersionBuild()
	return _u
}

// SetLastVerified sets the "last_verified" field.
func (_u *DBPackageUpdateOne) SetLastVerified(v time.Time) *DBPackageUpdateOne {
	_u.mutation.SetLastVerified(v)
	return _u
}

// SetNillableLastVerified sets the "last_verified" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableLastVerified(v *time.Time) *DBPackageUpdateOne {
	if v != nil {
		_u.SetLastVerified(*v)
	}
	return _u
}

// ClearLastVerified clears the value of the "last_verified" field.
func (_u *DBPackageUpdateOne) ClearLastVerified() *DBPackageUpdateOne {
	_u.mutation.ClearLastVerified()
	return _u
}

// SetDebugSymbols sets the "debug_symbols" field.
func (_u *DBPackageUpdateOne) SetDebugSymbols(v dbpackage.DebugSymbols) *DBPackageUpdateOne {
	_u.mutation.SetDebugSymbols(v)
	return _u
}

// SetNillableDebugSymbols sets the "debug_symbols" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableDebugSymbols(v *dbpackage.DebugSymbols) *DBPackageUpdateOne {
	if v != nil {
		_u.SetDebugSymbols(*v)
	}
	return _u
}

// ClearDebugSymbols clears the value of the "debug_symbols" field.
func (_u *DBPackageUpdateOne) ClearDebugSymbols() *DBPackageUpdateOne {
	_u.mutation.ClearDebugSymbols()
	return _u
}

// SetMaxRss sets the "max_rss" field.
func (_u *DBPackageUpdateOne) SetMaxRss(v int64) *DBPackageUpdateOne {
	_u.mutation.ResetMaxRss()
	_u.mutation.SetMaxRss(v)
	return _u
}

// SetNillableMaxRss sets the "max_rss" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableMaxRss(v *int64) *DBPackageUpdateOne {
	if v != nil {
		_u.SetMaxRss(*v)
	}
	return _u
}

// AddMaxRss adds value to the "max_rss" field.
func (_u *DBPackageUpdateOne) AddMaxRss(v int64) *DBPackageUpdateOne {
	_u.mutation.AddMaxRss(v)
	return _u
}

// ClearMaxRss clears the value of the "max_rss" field.
func (_u *DBPackageUpdateOne) ClearMaxRss() *DBPackageUpdateOne {
	_u.mutation.ClearMaxRss()
	return _u
}

// SetUTime sets the "u_time" field.
func (_u *DBPackageUpdateOne) SetUTime(v int64) *DBPackageUpdateOne {
	_u.mutation.ResetUTime()
	_u.mutation.SetUTime(v)
	return _u
}

// SetNillableUTime sets the "u_time" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableUTime(v *int64) *DBPackageUpdateOne {
	if v != nil {
		_u.SetUTime(*v)
	}
	return _u
}

// AddUTime adds value to the "u_time" field.
func (_u *DBPackageUpdateOne) AddUTime(v int64) *DBPackageUpdateOne {
	_u.mutation.AddUTime(v)
	return _u
}

// ClearUTime clears the value of the "u_time" field.
func (_u *DBPackageUpdateOne) ClearUTime() *DBPackageUpdateOne {
	_u.mutation.ClearUTime()
	return _u
}

// SetSTime sets the "s_time" field.
func (_u *DBPackageUpdateOne) SetSTime(v int64) *DBPackageUpdateOne {
	_u.mutation.ResetSTime()
	_u.mutation.SetSTime(v)
	return _u
}

// SetNillableSTime sets the "s_time" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableSTime(v *int64) *DBPackageUpdateOne {
	if v != nil {
		_u.SetSTime(*v)
	}
	return _u
}

// AddSTime adds value to the "s_time" field.
func (_u *DBPackageUpdateOne) AddSTime(v int64) *DBPackageUpdateOne {
	_u.mutation.AddSTime(v)
	return _u
}

// ClearSTime clears the value of the "s_time" field.
func (_u *DBPackageUpdateOne) ClearSTime() *DBPackageUpdateOne {
	_u.mutation.ClearSTime()
	return _u
}

// SetIoIn sets the "io_in" field.
func (_u *DBPackageUpdateOne) SetIoIn(v int64) *DBPackageUpdateOne {
	_u.mutation.ResetIoIn()
	_u.mutation.SetIoIn(v)
	return _u
}

// SetNillableIoIn sets the "io_in" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableIoIn(v *int64) *DBPackageUpdateOne {
	if v != nil {
		_u.SetIoIn(*v)
	}
	return _u
}

// AddIoIn adds value to the "io_in" field.
func (_u *DBPackageUpdateOne) AddIoIn(v int64) *DBPackageUpdateOne {
	_u.mutation.AddIoIn(v)
	return _u
}

// ClearIoIn clears the value of the "io_in" field.
func (_u *DBPackageUpdateOne) ClearIoIn() *DBPackageUpdateOne {
	_u.mutation.ClearIoIn()
	return _u
}

// SetIoOut sets the "io_out" field.
func (_u *DBPackageUpdateOne) SetIoOut(v int64) *DBPackageUpdateOne {
	_u.mutation.ResetIoOut()
	_u.mutation.SetIoOut(v)
	return _u
}

// SetNillableIoOut sets the "io_out" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableIoOut(v *int64) *DBPackageUpdateOne {
	if v != nil {
		_u.SetIoOut(*v)
	}
	return _u
}

// AddIoOut adds value to the "io_out" field.
func (_u *DBPackageUpdateOne) AddIoOut(v int64) *DBPackageUpdateOne {
	_u.mutation.AddIoOut(v)
	return _u
}

// ClearIoOut clears the value of the "io_out" field.
func (_u *DBPackageUpdateOne) ClearIoOut() *DBPackageUpdateOne {
	_u.mutation.ClearIoOut()
	return _u
}

// SetTagRev sets the "tag_rev" field.
func (_u *DBPackageUpdateOne) SetTagRev(v string) *DBPackageUpdateOne {
	_u.mutation.SetTagRev(v)
	return _u
}

// SetNillableTagRev sets the "tag_rev" field if the given value is not nil.
func (_u *DBPackageUpdateOne) SetNillableTagRev(v *string) *DBPackageUpdateOne {
	if v != nil {
		_u.SetTagRev(*v)
	}
	return _u
}

// ClearTagRev clears the value of the "tag_rev" field.
func (_u *DBPackageUpdateOne) ClearTagRev() *DBPackageUpdateOne {
	_u.mutation.ClearTagRev()
	return _u
}

// Mutation returns the DBPackageMutation object of the builder.
func (_u *DBPackageUpdateOne) Mutation() *DBPackageMutation {
	return _u.mutation
}

// Where appends a list predicates to the DBPackageUpdate builder.
func (_u *DBPackageUpdateOne) Where(ps ...predicate.DBPackage) *DBPackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DBPackageUpdateOne) Select(field string, fields ...string) *DBPackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DBPackage entity.
func (_u *DBPackageUpdateOne) Save(ctx context.Context) (*DBPackage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DBPackageUpdateOne) SaveX(ctx context.Context) *DBPackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DBPackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DBPackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DBPackageUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dbpackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DBPackage.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Repository(); ok {
		if err := dbpackage.RepositoryValidator(v); err != nil {
			return &ValidationError{Name: "repository", err: fmt.Errorf(`ent: validator failed for field "DBPackage.repository": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lto(); ok {
		if err := dbpackage.LtoValidator(v); err != nil {
			return &ValidationError{Name: "lto", err: fmt.Errorf(`ent: validator failed for field "DBPackage.lto": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DebugSymbols(); ok {
		if err := dbpackage.DebugSymbolsValidator(v); err != nil {
			return &ValidationError{Name: "debug_symbols", err: fmt.Errorf(`ent: validator failed for field "DBPackage.debug_symbols": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DBPackageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DBPackageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DBPackageUpdateOne) sqlSave(ctx context.Context) (_node *DBPackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dbpackage.Table, dbpackage.Columns, sqlgraph.NewFieldSpec(dbpackage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DBPackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dbpackage.FieldID)
		for _, f := range fields {
			if !dbpackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dbpackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Packages(); ok {
		_spec.SetField(dbpackage.FieldPackages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPackages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dbpackage.FieldPackages, value)
		})
	}
	if _u.mutation.PackagesCleared() {
		_spec.ClearField(dbpackage.FieldPackages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dbpackage.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(dbpackage.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.SkipReason(); ok {
		_spec.SetField(dbpackage.FieldSkipReason, field.TypeString, value)
	}
	if _u.mutation.SkipReasonCleared() {
		_spec.ClearField(dbpackage.FieldSkipReason, field.TypeString)
	}
	if value, ok := _u.mutation.Repository(); ok {
		_spec.SetField(dbpackage.FieldRepository, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(dbpackage.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(dbpackage.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.RepoVersion(); ok {
		_spec.SetField(dbpackage.FieldRepoVersion, field.TypeString, value)
	}
	if _u.mutation.RepoVersionCleared() {
		_spec.ClearField(dbpackage.FieldRepoVersion, field.TypeString)
	}
	if value, ok := _u.mutation.BuildTimeStart(); ok {
		_spec.SetField(dbpackage.FieldBuildTimeStart, field.TypeTime, value)
	}
	if _u.mutation.BuildTimeStartCleared() {
		_spec.ClearField(dbpackage.FieldBuildTimeStart, field.TypeTime)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(dbpackage.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UpdatedCleared() {
		_spec.ClearField(dbpackage.FieldUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Lto(); ok {
		_spec.SetField(dbpackage.FieldLto, field.TypeEnum, value)
	}
	if _u.mutation.LtoCleared() {
		_spec.ClearField(dbpackage.FieldLto, field.TypeEnum)
	}
	if value, ok := _u.mutation.LastVersionBuild(); ok {
		_spec.SetField(dbpackage.FieldLastVersionBuild, field.TypeString, value)
	}
	if _u.mutation.LastVersionBuildCleared() {
		_spec.ClearField(dbpackage.FieldLastVersionBuild, field.TypeString)
	}
	if value, ok := _u.mutation.LastVerified(); ok {
		_spec.SetField(dbpackage.FieldLastVerified, field.TypeTime, value)
	}
	if _u.mutation.LastVerifiedCleared() {
		_spec.ClearField(dbpackage.FieldLastVerified, field.TypeTime)
	}
	if value, ok := _u.mutation.DebugSymbols(); ok {
		_spec.SetField(dbpackage.FieldDebugSymbols, field.TypeEnum, value)
	}
	if _u.mutation.DebugSymbolsCleared() {
		_spec.ClearField(dbpackage.FieldDebugSymbols, field.TypeEnum)
	}
	if value, ok := _u.mutation.MaxRss(); ok {
		_spec.SetField(dbpackage.FieldMaxRss, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxRss(); ok {
		_spec.AddField(dbpackage.FieldMaxRss, field.TypeInt64, value)
	}
	if _u.mutation.MaxRssCleared() {
		_spec.ClearField(dbpackage.FieldMaxRss, field.TypeInt64)
	}
	if value, ok := _u.mutation.UTime(); ok {
		_spec.SetField(dbpackage.FieldUTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUTime(); ok {
		_spec.AddField(dbpackage.FieldUTime, field.TypeInt64, value)
	}
	if _u.mutation.UTimeCleared() {
		_spec.ClearField(dbpackage.FieldUTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.STime(); ok {
		_spec.SetField(dbpackage.FieldSTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSTime(); ok {
		_spec.AddField(dbpackage.FieldSTime, field.TypeInt64, value)
	}
	if _u.mutation.STimeCleared() {
		_spec.ClearField(dbpackage.FieldSTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.IoIn(); ok {
		_spec.SetField(dbpackage.FieldIoIn, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIoIn(); ok {
		_spec.AddField(dbpackage.FieldIoIn, field.TypeInt64, value)
	}
	if _u.mutation.IoInCleared() {
		_spec.ClearField(dbpackage.FieldIoIn, field.TypeInt64)
	}
	if value, ok := _u.mutation.IoOut(); ok {
		_spec.SetField(dbpackage.FieldIoOut, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIoOut(); ok {
		_spec.AddField(dbpackage.FieldIoOut, field.TypeInt64, value)
	}
	if _u.mutation.IoOutCleared() {
		_spec.ClearField(dbpackage.FieldIoOut, field.TypeInt64)
	}
	if value, ok := _u.mutation.TagRev(); ok {
		_spec.SetField(dbpackage.FieldTagRev, field.TypeString, value)
	}
	if _u.mutation.TagRevCleared() {
		_spec.ClearField(dbpackage.FieldTagRev, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DBPackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dbpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
